### ISSUE TITLE
[Dreambox TWO] Possible to use wireless card of the host?

### ISSUE THREAD

**Issue by nrpetonr** [AlbrechtL/openwrt-docker#10]
hi, the container is working, nice job.

i am considering use case in which wireless card of the host would serve as access point (basically dumb AP as i have only one ethernet port). will it passthrough wireless card or i need to do something to enable that? i cant seem to activate wireless properly under openwrt. hereinafter some screenshots. thanks for your hints.

![Screenshot 2024-12-11 134200](https://github.com/user-attachments/assets/a04287b8-98de-483b-86b0-550424b9fd10)

![Screenshot 2024-12-11 134808](https://github.com/user-attachments/assets/f6ef2edd-7f14-4813-8986-c25211da89f3)

**Comment by AlbrechtL** [comment]
I expect that your wireless card is USB, right? And you set the `USB_1` environment variables inside the compose file?
https://github.com/AlbrechtL/openwrt-docker/blob/ef779d30065de8791e70b34934e42eb2c1fc5fbc/docker-compose.yml#L31-L34

Then you need to install the correct kernel modules for your USB dongle. To prove if everything is working, you can run `lsusb` or `dmesg` and you should see your USB Wi-Fi dongle. Afterward, you should also see it in the LuCI web interface.

**Comment by nrpetonr** [comment]
actually not usb dongle. it is internal dual band wifi. unfortunately i am running limited linux distribution on dreambox two with old kernel Linux dreambox 4.9 and standard commands to find more about used wifi module do not work. the only way to find anthing was to use dmesg within running opewrt itself. probably stucked...

**Comment by AlbrechtL** [comment]
Usually also internal Wi-Fi cards are using USB. Does `lsusb` on your host system reports a Wi-Fi USB device?

**Comment by nrpetonr** [comment]
no, both are usb hubs

Bus 001 Device 001: ID 1d6b:0002
Bus 002 Device 001: ID 1d6b:0003

**Comment by AlbrechtL** [comment]
Closed because of inactivity.
